import assert from 'node:assert/strict';
import { markdown, guideSections } from '../scripts/markdown.mjs';
assert.ok(markdown.render('```math\n\\widetilde u_i = \\frac{\\overline{\\rho u_i}}{\\overline\\rho}\n```').includes('<math'));
assert.ok(!markdown.render('<script>alert(1)</script>').includes('<script>'));
assert.ok(markdown.render('## Density weighting').includes('id="density-weighting"'));
assert.ok(markdown.render('Density $\\rho$ is positive.').includes('<math'));
assert.ok(!markdown.render('An unmatched $ remains.').includes('<math'));
assert.throws(() => markdown.render('$\\notARealCommand$'), /ParseError/);
const sections = guideSections('## 01 — Flow\n\nSee [source][s].\n\n### Density\n\n$\\rho$\n\n## References\n\n- Source\n\n[s]: https://example.com');
assert.deepEqual(sections.map(s => s.id), ['section-01','references']);
assert.ok(sections[0].html.includes('href="https://example.com"') && sections[0].html.includes('<h3') && sections[0].html.includes('<math'), 'Preserve global citation definitions and subheadings when grouping sections');
console.log('Content checks passed: inline/display math, malformed math, literal HTML, heading links, and section grouping.');
const local = guideSections('## 01 — Flow\n\nSee [source][s].\n\n### Sources\n\n- [Full citation][s]\n\n## 02 — Closure\n\nBody\n\n### Sources\n\n- [Full citation][s]\n\n[s]: https://example.com');
assert.equal(local.length, 2);
assert.ok(local.every(s => s.sources.includes('href="https://example.com"') && !s.html.includes('Full citation')), 'Separate Sources while preserving shared citation definitions');
assert.ok(markdown.render('```figure\nsrc: /assets/figures/test.svg\nalt: "A <field>"\nwidth: 600\nheight: 300\ncaption: "See [paper](https://example.com)."\n```').includes('<figcaption>See <a'));
assert.throws(() => markdown.render('```figure\nsrc: https://example.com/image.png\n```'), /Figures require/);
